stages:
  - build
  - deploy

build_job:
  stage: build
  variables:
    IIS_VERSION_SUFFIX: $CI_PIPELINE_ID
  script:
    - export IIS_SOURCE_REVISION_ID=`git describe --always --tags --dirty`
    - dotnet publish IIS/IIS.Core/IIS.Core.csproj -c Release -o publish/core
  artifacts:
    paths:
    - publish
    expire_in: 1 month

  tags:
    - ci
  only:
    - master
    - /^v.+$/
    - /^sprint\..+$/

.deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
    GIT_CHECKOUT: "false"
    EXTRA_VARS: "artifacts_path=$CI_PROJECT_DIR"
  script:
    - cd /home/gitlab-runner/ansible
    - ansible-playbook app_api_net.yml -e '@./vars/$DEPLOYMENT_FILE' -e '$EXTRA_VARS'
    - rm -rf $CI_PROJECT_DIR/*
  tags:
    - ansible
  only:
    - master
    - /^v.+$/
    - /^sprint\..+$/

deploy_contour_dev: &deploy_contour_dev
  extends: .deploy
  variables:
    DEPLOYMENT_FILE: dev_con.yml
  environment:
    name: dev_contour
    url: http://contour-dev-01.contour.net

deploy_contour_dev_manual:
  <<: *deploy_contour_dev
  when: manual
  only:
    - /^v.+$/
    - /^sprint\..+$/

deploy_od_dev: &deploy_od_dev
  extends: .deploy
  variables:
    DEPLOYMENT_FILE: dev_od.yml
  environment:
    name: dev_odysseus
    url: http://od-dev.contour.net

deploy_od_dev_manual:
  <<: *deploy_od_dev
  when: manual
  only:
    - /^v.+$/
    - /^sprint\..+$/

deploy_contour_qa:
  extends: .deploy
  variables:
    DEPLOYMENT_FILE: qa_con.yml
    EXTRA_VARS: "tag_name=$TAG_NAME ontology_clear=$ONTOLOGY_NAME"
  environment:
    name: qa_contour
    url: http://qa-app.contour.net
  when: manual

deploy_contour_stage:
  extends: .deploy
  variables:
    DEPLOYMENT_FILE: stage_con.yml
    EXTRA_VARS: "tag_name=$TAG_NAME ontology_clear=$ONTOLOGY_NAME"
  environment:
    name: stage_contour
    url: http://192.168.88.164
  when: manual

deploy_od_stage:
  extends: .deploy
  variables:
    DEPLOYMENT_FILE: stage_od.yml
    EXTRA_VARS: "tag_name=$TAG_NAME ontology_clear=$ONTOLOGY_NAME"
  environment:
    name: stage_odysseus
    url: http://stage-app.odysseus.lcl
  when: manual

deploy_od_qa:
  extends: .deploy
  variables:
    DEPLOYMENT_FILE: qa_od.yml
    EXTRA_VARS: "tag_name=$TAG_NAME ontology_clear=$ONTOLOGY_NAME"
  environment:
    name: qa_odysseus
    url: http://qa-app.odysseus.lcl
  when: manual