stages:
  - build
  - deploy
  
build_job:
  stage: build
  script:
    - cd IIS/ && sh ./startup
    - ls
  artifacts:
    paths:
    - publish
    expire_in: 1 week
    
  tags:
    - ci
    
deploy_job:
  stage: deploy
  script:
    - ls
    
  when: manual
  tags:
    - ci

  