build:
  stage: build
  
  script:
    - ls
    - mv -f IIS/iis-api.net /home/gitlab-runner/
    - cd /home/gitlab-runner/iis-api.net/IIS/
    - bash /home/gitlab-runner/sr.sh
    - export ASPNETCORE_ENVIRONMENT=Staging && dotnet publish IIS.Core/IIS.Core.csproj -o ../publish/web
    
  only:
    - master
  
  
  tags:
    - dev