stages:
  - build
  - deploy
  
build_job:
  stage: build
  script:
    - cd IIS 
    - dotnet publish IIS.Core/IIS.Core.csproj -o ../publish/core --version-suffix $(git rev-parse --short HEAD)
  artifacts:
    paths:
    - IIS/publish
    expire_in: 1 month
    
  tags:
    - ci
  only: 
    - master
    - /^v*$/
    - /^sprint.*$/
    
.deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
    GIT_CHECKOUT: "false"
  script:
    - cd /home/gitlab-runner/ansible
    - ansible-playbook app_api_net.yml -e '@./vars/$DEPLOYMENT_FILE' -e 'artifacts_path=$CI_PROJECT_DIR'
    - rm -rf $CI_PROJECT_DIR/*

  tags:
    - ansible
  only: 
    - master  
    
deploy_dev:
  extends: .deploy
  variables:
    DEPLOYMENT_FILE: dev_con.yml
  environment:
    name: dev_contour
    url: http://contour-dev-01.contour.net


deploy_od:
  extends: .deploy
  variables:
    DEPLOYMENT_FILE: dev_od.yml
  environment:
    name: dev_odysseus
    url: http://od-dev.contour.net

deploy_qa:
  extends: .deploy
  variables:
    DEPLOYMENT_FILE: qa_con.yml
  environment:
    name: qa_contour
    url: http://qa-app.contour.net
  when: manual
  
deploy_stage:
  extends: .deploy
  variables:
    DEPLOYMENT_FILE: stage_con.yml
  environment:
    name: stage_contour
    url: http://192.168.88.164
  when: manual
  
deploy_stage_od:
  extends: .deploy
  variables:
    DEPLOYMENT_FILE: stage_od.yml
  environment:
    name: stage_odysseus
    url: http://stage-app.odysseus.lcl
  when: manual