stages:
  - build
  - deploy
  
build_job:
  stage: build
  script:
    - cd IIS/ && sh ./startup
    - ls
  artifacts:
    paths:
    - IIS/publish
    expire_in: 1 week
    
  tags:
    - ci
    
deploy_dev:
  stage: deploy
  script:
    - cd /home/gitlab-runner/ansible
    - "ansible-playbook app_api_net_dev.yml --extra-vars \"HOST=contour-dev tag_name=$CI_COMMIT_REF_NAME job_name=build_job\""
    
  tags:
    - ansible
  only: master  
