stages:
  - build
  - deploy
  
build_job:
  stage: build
  script:
    - cd IIS 
    - dotnet publish IIS.Core/IIS.Core.csproj -o ../publish/core
  artifacts:
    paths:
    - IIS/publish
    expire_in: 1 week
    
  tags:
    - ci
  only: 
    - master
    
deploy_dev:
  stage: deploy
  variables:
    GIT_STRATEGY: none
    GIT_CHECKOUT: "false"
  script:
    - cd /home/gitlab-runner/ansible
    - "ansible-playbook app_api_net_dev.yml --extra-vars \"HOST=contour-dev tag_name=$CI_COMMIT_REF_NAME job_name=build_job\""
    
  tags:
    - ansible
  only: 
    - master  
