stages:
  - build
  - deploy
  
build_job:
  stage: build
  script:
    - cd IIS 
    - dotnet publish IIS.Core/IIS.Core.csproj -o ../publish/core --version-suffix $(git rev-parse --short HEAD)
  artifacts:
    paths:
    - IIS/publish
    expire_in: 1 month
    
  tags:
    - ci
  only: 
    - master
    - /^v.+$/
    - /^sprint\..+$/
    
.deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
    GIT_CHECKOUT: "false"
  before_script:
    - cd /home/gitlab-runner/ansible
  tags:
    - ansible
  only: 
    - master  
    
deploy_dev:
  extends: .deploy
  script:
    - ansible-playbook app_api_net.yml --extra-vars "HOST=contour-dev artifacts_path=$CI_PROJECT_DIR env_file=web_dev"
  environment:
    name: dev_contour
    url: http://contour-dev-01.contour.net


deploy_od:
  extends: .deploy
  script:
    - ansible-playbook app_api_net.yml --extra-vars "HOST=od-dev artifacts_path=$CI_PROJECT_DIR env_file=web_dev_od"
  environment:
    name: dev_odysseus
    url: http://od-dev.contour.net
      
  
