stages:
  - build
  - deploy
  
build_job:
  stage: build
  script:
    - cd IIS 
    - dotnet publish IIS.Core/IIS.Core.csproj -o ../publish/core --version-suffix $(git rev-parse --short HEAD)
  artifacts:
    paths:
    - IIS/publish
    expire_in: 1 week
    
  tags:
    - ci
#  only: 
#    - master
    
.deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
    GIT_CHECKOUT: "false"
  before_script:
    - cd /home/gitlab-runner/ansible
  tags:
    - ansible
#  only: 
#    - master  
    
deploy_dev:
  extends: .deploy
  stage: deploy
  script:
    - ansible-playbook app_api_net_dev.yml --extra-vars "HOST=envtest artifacts_path=$CI_PROJECT_DIR"
  environment:
    name: stage
    url: http://192.168.88.82

