// <auto-generated />
using System;
using Iis.MaterialDistributor.DataModel.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Iis.MaterialDistributor.DataModel.Migrations
{
    [DbContext(typeof(MaterialDistributorContext))]
    [Migration("20220124133941_AddVariableCoefficientEntity")]
    partial class AddVariableCoefficientEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Iis.MaterialDistributor.DataModel.Entities.PermanentCriteriaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PermanentCriterias");
                });

            modelBuilder.Entity("Iis.MaterialDistributor.DataModel.Entities.VariableCoefficientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Coefficient")
                        .HasColumnType("integer");

                    b.Property<int>("OffsetHours")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("VariableCoefficients");
                });
#pragma warning restore 612, 618
        }
    }
}
